// Generated by CoffeeScript 1.4.0
(function() {
  var AWS, Config, Pile, civi, d, https, slack, sqs,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __slice = [].slice;

  https = require('https');

  AWS = require('aws-sdk');

  sqs = new AWS.SQS({
    region: 'us-west-1'
  });

  Config = {
    civi_queue: process.env['CIVI_QUEUE'],
    slack_queue: process.env['SLACK_QUEUE'],
    token: process.env['TOKEN'],
    civi_types: ["member.deleted", "petition.launched", "signature.created", "signature.deleted", "signature.confirmed", "unsubscribe.created", "attendee.created", "attendee.updated"],
    slack_types: ["blast_email.created", "event.created", "event.updated", "local_chapter.organiser_request.created", "petition.flagged", "petition.launched", "petition.launched.ham", "petition.launched.requires_moderation", "petition.reactivated", "petition.updated", "petition.updated.requires_moderation"]
  };

  d = function(o) {
    return JSON.stringify(o);
  };

  Pile = (function() {

    function Pile(queue_url, types) {
      this.url = queue_url;
      this.pile_types = types;
    }

    Pile.prototype.result = function(err, data) {
      return console.log("SQS error is " + err + ", data is " + (d(data)));
    };

    Pile.prototype.pile = function(obj, callback) {
      var _this = this;
      console.log("Going to pile " + (d(obj)));
      return sqs.sendMessage({
        MessageBody: JSON.stringify(obj),
        QueueUrl: this.url
      }, function(err, data) {
        return _this.result(err, data);
      });
    };

    Pile.prototype.event = function(event, context, callback) {
      var _ref;
      console.log("event: " + (d(event)));
      if (_ref = event.type, __indexOf.call(this.pile_types, _ref) >= 0) {
        this.pile(event, callback);
        return callback(null, true);
      } else {
        return callback(null, false);
      }
    };

    return Pile;

  })();

  civi = new Pile(Config.civi_queue, Config.civi_types);

  slack = new Pile(Config.slack_queue, Config.slack_types);

  exports.event = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    civi.event.apply(civi, args);
    return slack.event.apply(slack, args);
  };

}).call(this);
